export const _s = {
    canvas: document.querySelector('#canvas'),
    ctx: canvas.getContext('2d'),
    div: document.querySelector('#div'),
    tiles: document.querySelector('#tiles'),
    sprites: document.querySelector('#tiles'),
    TILEMAP_WIDTH: 20,
    TILEMAP_HEIGHT: 20,
    TILE_WIDTH: 16,
    TILE_HEIGHT: 16,
    DRAW_TILE_WIDTH: 64,
    DRAW_TILE_HEIGHT: 64,
    DRAW_PLAYER_WIDTH: 64,
    DRAW_PLAYER_HEIGHT: 64,
    GRIDMAP_WIDTH: 30,
    GRIDMAP_HEIGHT: 30,
    DRAW_GRIDMAP_WIDTH: 10,
    DRAW_GRIDMAP_HEIGHT: 10,
    PLATFORM_TYPES: [],
    WALK_SPEED: 2,
    WALK_RESISTANCE: 0.8,
    GRAVITY: -0.5,
    JUMP_HEIGHT: 10,
    mod: (a,b) => ((a%b)+b)%b,
    keyPresses: [],
    gridmap: [],
    playerX: 0,
    playerY: 0,
    playerXv: 0,
    playerYv: 0,
    camX: 0,
    camY: 0
}